/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 c.glb -t -r ./ 
*/

import * as THREE from 'three'
import React, { useRef, forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Group } from 'three';

type GLTFResult = GLTF & {
  nodes: {
    Curve011: THREE.Mesh
    Curve012: THREE.Mesh
    Curve013: THREE.Mesh
    Curve014: THREE.Mesh
  }
  materials: {
    ['Mat.001']: THREE.MeshStandardMaterial
    ['Mat.002']: THREE.MeshStandardMaterial
    Mat: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

type LogoProps = JSX.IntrinsicElements['group'] & {
  // Aquí puedes añadir cualquier otra prop personalizada si es necesario
};

export const C = forwardRef<Group, LogoProps>((props, ref) => {
  const { nodes, materials } = useGLTF('models/c.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.Curve011.geometry} material={materials['Mat.001']} position={[-0.013, 0, 0.013]} scale={0.767} />
      <mesh geometry={nodes.Curve012.geometry} material={materials['Mat.002']} position={[-0.013, 0, 0.013]} scale={0.767} />
      <mesh geometry={nodes.Curve013.geometry} material={materials.Mat} position={[-0.013, 0, 0.013]} scale={0.767} />
      <mesh geometry={nodes.Curve014.geometry} material={materials.Mat} position={[-0.013, 0, 0.013]} scale={0.767} />
    </group>
  )
});

useGLTF.preload('models/c.glb')

