/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 github.glb -t -r ./ 
*/

import * as THREE from 'three'
import React, { useRef, forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Group } from 'three';

type GLTFResult = GLTF & {
  nodes: {
    Curve006: THREE.Mesh
    Curve007: THREE.Mesh
  }
  materials: {
    Mat: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

type LogoProps = JSX.IntrinsicElements['group'] & {
  // Aquí puedes añadir cualquier otra prop personalizada si es necesario
};

export const CV = forwardRef<Group, LogoProps>((props, ref) => {
  const { nodes, materials } = useGLTF('models/cv.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Curve006.geometry} material={materials.Mat} position={[-0.054, 0, 0.036]} scale={2.057} />
      <mesh castShadow receiveShadow geometry={nodes.Curve007.geometry} material={materials.Mat} position={[-0.054, 0, 0.036]} scale={2.057} />
    </group>
  )
});

useGLTF.preload('models/cv.glb')
