/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 lemming.glb -t -r ./ 
*/

import * as THREE from 'three'
import React, { useRef, forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Group } from 'three';

type GLTFResult = GLTF & {
  nodes: {
    lemming_1_1_0png_11_0_mesh: THREE.Mesh
    lemming_1_1_0png_11_0_mesh_1: THREE.Mesh
    lemming_1_1_0png_11_0_mesh_2: THREE.Mesh
    lemming_1_1_1png_8_0_mesh: THREE.Mesh
    lemming_1_1_1png_8_0_mesh_1: THREE.Mesh
    lemming_1_1_1png_8_0_mesh_2: THREE.Mesh
    lemming_1_1_2png_7_0_mesh: THREE.Mesh
    lemming_1_1_2png_7_0_mesh_1: THREE.Mesh
    lemming_1_1_2png_7_0_mesh_2: THREE.Mesh
    lemming_1_1_3png_7_0_mesh001: THREE.Mesh
    lemming_1_1_3png_7_0_mesh001_1: THREE.Mesh
    lemming_1_1_3png_7_0_mesh001_2: THREE.Mesh
    lemming_1_1_4png_8_0_mesh: THREE.Mesh
    lemming_1_1_4png_8_0_mesh_1: THREE.Mesh
    lemming_1_1_4png_8_0_mesh_2: THREE.Mesh
    lemming_1_1_5png_8_0_mesh: THREE.Mesh
    lemming_1_1_5png_8_0_mesh_1: THREE.Mesh
    lemming_1_1_5png_8_0_mesh_2: THREE.Mesh
    lemming_1_1_6png_7_0_mesh: THREE.Mesh
    lemming_1_1_6png_7_0_mesh_1: THREE.Mesh
    lemming_1_1_6png_7_0_mesh_2: THREE.Mesh
    lemming_1_1_7png_7_0_mesh: THREE.Mesh
    lemming_1_1_7png_7_0_mesh_1: THREE.Mesh
    lemming_1_1_7png_7_0_mesh_2: THREE.Mesh
    lemming_1_1_8png_9_0_mesh: THREE.Mesh
    lemming_1_1_8png_9_0_mesh_1: THREE.Mesh
    lemming_1_1_8png_9_0_mesh_2: THREE.Mesh
  }
  materials: {
    White: THREE.MeshStandardMaterial
    Blue: THREE.MeshStandardMaterial
    Green: THREE.MeshStandardMaterial
  }
}


type Props = JSX.IntrinsicElements['group'] & {
};

export const Lemming = forwardRef<Group, Props>((props, ref) => {
  const { nodes, materials } = useGLTF('models/lemming.glb') as GLTFResult

  const { useState, useEffect } = React;

  const [frame, setFrame] = useState(0);

  const totalFrames = 8; // 0 to 8
  const duration = 2000; // duración total en ms (ajustable)
  const reverse = false; // poner en true para animar al revés

  useEffect(() => {
    let animationFrame: number;
    let startTime: number | null = null;

    function animate(now: number) {
      if (startTime === null) startTime = now;
      const elapsed = now - startTime;
      const progress = (elapsed % duration) / duration;
      let currentFrame = Math.floor(progress * totalFrames);

      if (reverse) {
        currentFrame = totalFrames - 1 - currentFrame;
      }

      setFrame(currentFrame);
      animationFrame = requestAnimationFrame(animate);
    }

    animationFrame = requestAnimationFrame(animate);
    return () => cancelAnimationFrame(animationFrame);
  }, [duration, reverse, totalFrames]);


  return (
    <group ref={ref} {...props} dispose={null}>
      <group position={[11, 0, -11]} visible={frame == 0}>
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_0png_11_0_mesh.geometry} material={materials.White} />
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_0png_11_0_mesh_1.geometry} material={materials.Blue} />
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_0png_11_0_mesh_2.geometry} material={materials.Green} />
      </group>
      <group position={[8, 0, -5]} visible={frame == 1}>
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_1png_8_0_mesh.geometry} material={materials.White} />
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_1png_8_0_mesh_1.geometry} material={materials.Blue} />
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_1png_8_0_mesh_2.geometry} material={materials.Green} />
      </group>
      <group position={[7, 0, -5]} visible={frame == 2}>
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_2png_7_0_mesh.geometry} material={materials.White} />
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_2png_7_0_mesh_1.geometry} material={materials.Blue} />
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_2png_7_0_mesh_2.geometry} material={materials.Green} />
      </group>
      <group position={[7, 0, -6]} visible={frame == 3}>
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_3png_7_0_mesh001.geometry} material={materials.White} />
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_3png_7_0_mesh001_1.geometry} material={materials.Blue} />
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_3png_7_0_mesh001_2.geometry} material={materials.Green} />
      </group>
      <group position={[8, 0, -6]} visible={frame == 4}>
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_4png_8_0_mesh.geometry} material={materials.White} />
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_4png_8_0_mesh_1.geometry} material={materials.Blue} />
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_4png_8_0_mesh_2.geometry} material={materials.Green} />
      </group>
      <group position={[8, 0, -5]} visible={frame == 5}>
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_5png_8_0_mesh.geometry} material={materials.White} />
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_5png_8_0_mesh_1.geometry} material={materials.Blue} />
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_5png_8_0_mesh_2.geometry} material={materials.Green} />
      </group>
      <group position={[7, 0, -5]} visible={frame == 6}>
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_6png_7_0_mesh.geometry} material={materials.White} />
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_6png_7_0_mesh_1.geometry} material={materials.Blue} />
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_6png_7_0_mesh_2.geometry} material={materials.Green} />
      </group>
      <group position={[7, 0, -5]} visible={frame == 7}>
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_7png_7_0_mesh.geometry} material={materials.White} />
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_7png_7_0_mesh_1.geometry} material={materials.Blue} />
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_7png_7_0_mesh_2.geometry} material={materials.Green} />
      </group>
      <group position={[9, 0, -5]} visible={frame == 8}>
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_8png_9_0_mesh.geometry} material={materials.White} />
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_8png_9_0_mesh_1.geometry} material={materials.Blue} />
        <mesh castShadow receiveShadow geometry={nodes.lemming_1_1_8png_9_0_mesh_2.geometry} material={materials.Green} />
      </group>
    </group>
  )
});

useGLTF.preload('models/lemming.glb')
