/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 linkedin.glb -t -r ./ 
*/

import * as THREE from 'three'
import React, { useRef, forwardRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Group } from 'three';

type GLTFResult = GLTF & {
  nodes: {
    XMLID_802_: THREE.Mesh
    XMLID_803_: THREE.Mesh
    XMLID_804_: THREE.Mesh
  }
  materials: {
    Mat: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

type LogoProps = JSX.IntrinsicElements['group'] & {
  // Aquí puedes añadir cualquier otra prop personalizada si es necesario
};

export const Linkedin = forwardRef<Group, LogoProps>((props, ref) => {
  const [isHovered, setIsHovered] = useState(false);
  const { nodes, materials } = useGLTF('models/linkedin.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.XMLID_802_.geometry} material={materials.Mat} position={isHovered ? [-0.012, 0, 0.0115] : [-0.012, 0, 0.01]} scale={isHovered ? 0.122 : 0.112}
        onPointerEnter={(event) => (event.stopPropagation(), setIsHovered(true))}
        onPointerLeave={() => setIsHovered(false)} />
      <mesh castShadow receiveShadow geometry={nodes.XMLID_803_.geometry} material={materials.Mat} position={isHovered ? [-0.012, 0, 0.0115] : [-0.012, 0, 0.01]} scale={isHovered ? 0.122 : 0.112}
        onPointerEnter={(event) => (event.stopPropagation(), setIsHovered(true))}
        onPointerLeave={() => setIsHovered(false)} />
      <mesh castShadow receiveShadow geometry={nodes.XMLID_804_.geometry} material={materials.Mat} position={isHovered ? [-0.012, 0, 0.0115] : [-0.012, 0, 0.01]} scale={isHovered ? 0.122 : 0.112}
        onPointerEnter={(event) => (event.stopPropagation(), setIsHovered(true))}
        onPointerLeave={() => setIsHovered(false)} />
    </group>
  )
});

useGLTF.preload('models/linkedin.glb')
