/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 piano.glb -t -r ./ 
*/

import * as THREE from 'three'
import React, { useRef, forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Group } from 'three';

type GLTFResult = GLTF & {
  nodes: {
    _1: THREE.Mesh
    _2: THREE.Mesh
    _21: THREE.Mesh
    _3: THREE.Mesh
    _4: THREE.Mesh
  }
  materials: {
    ['Piano Material']: THREE.MeshStandardMaterial
    ['Wood-10']: THREE.MeshStandardMaterial
    ['Fluegel-02']: THREE.MeshStandardMaterial
    ['Fluegel-03']: THREE.MeshStandardMaterial
    ['Fluegel-04']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

type LogoProps = JSX.IntrinsicElements['group'] & {
  // Aquí puedes añadir cualquier otra prop personalizada si es necesario
};

export const Piano = forwardRef<Group, LogoProps>((props, ref) => {
  const { nodes, materials } = useGLTF('models/piano.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <group position={[0, -0.001, 0]} scale={0.088}>
        <mesh castShadow receiveShadow geometry={nodes._1.geometry} position={[-0.06, 12.762, -5.007]} scale={571.937} >
          <meshPhysicalMaterial
            color={new THREE.Color(0x000000)}
            roughness={0.6}
            metalness={0.2}
          />
        </mesh>
        <mesh castShadow receiveShadow geometry={nodes._2.geometry} material={materials['Wood-10']} position={[0.013, 6.591, -5.639]} scale={571.937} />
        <mesh castShadow receiveShadow geometry={nodes._21.geometry} material={materials['Fluegel-02']} position={[0.013, 6.591, -5.639]} scale={571.937} />
        <mesh castShadow receiveShadow geometry={nodes._3.geometry} position={[0.013, 9.65, 8.147]} scale={571.937}>
          <meshPhysicalMaterial
            color={new THREE.Color(0xaaaaaa)}
            roughness={0.3}
            metalness={0.1}
          />
        </mesh>
        <mesh castShadow receiveShadow geometry={nodes._4.geometry} material={materials['Fluegel-04']} position={[0.013, 9.79, 7.804]} scale={571.937} />
      </group>
    </group>
  )
});

useGLTF.preload('models/piano.glb')


