/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/rusty_spaceship.glb -t -r public 
Author: Sousinho (https://sketchfab.com/sousinho)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rusty-spaceship-502d0ff399d64eda8a7d932db619ce95
Title: Rusty Spaceship
*/

import * as THREE from 'three'
import React, { useRef, forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'
import { GLTF } from 'three-stdlib'
import { Group } from 'three';


type GLTFResult = GLTF & {
  nodes: {
    Cube001_spaceship_racer_0: THREE.Mesh
    Cylinder002_spaceship_racer_0: THREE.Mesh
    Cylinder003_spaceship_racer_0: THREE.Mesh
    Cube003_spaceship_racer_0: THREE.Mesh
    Cylinder004_spaceship_racer_0: THREE.Mesh
    Cube001_RExtr001_spaceship_racer_0: THREE.Mesh
    Cube001_RPanel003_spaceship_racer_0: THREE.Mesh
    Cube001_RPanel003_RExtr_spaceship_racer_0: THREE.Mesh
    Cube002_spaceship_racer_0: THREE.Mesh
    Cube001_RPanel001_spaceship_racer_0: THREE.Mesh
    Cube001_RPanel003_RExtr001_spaceship_racer_0: THREE.Mesh
    Cube005_cockpit_0: THREE.Mesh
    Sphere_cockpit_0: THREE.Mesh
  }
  materials: {
    spaceship_racer: THREE.MeshStandardMaterial
    cockpit: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

type SpaceShipProps = JSX.IntrinsicElements['group'] & {
  // Aquí puedes añadir cualquier otra prop personalizada si es necesario
};

export const RusticSpaceShip = forwardRef<Group, SpaceShipProps>((props, ref) => {
  const { nodes, materials } = useGLTF('models/rusty_spaceship.glb') as GLTFResult
  const position: [number, number, number] = [0, 0, 0];
  const rotation: [number, number, number] = [0, Math.PI / 3, 0];
  const scale = 0.13;
  return (
    <group ref={ref} {...props} scale={scale} dispose={null}>
      <group scale={0.005} rotation={rotation} position={position}>

        <mesh castShadow receiveShadow geometry={nodes.Cube001_spaceship_racer_0.geometry} material={materials.spaceship_racer} position={[739.257, -64.815, 64.771]} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder002_spaceship_racer_0.geometry} material={materials.spaceship_racer} position={[739.691, -59.39, -553.376]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder003_spaceship_racer_0.geometry} material={materials.spaceship_racer} position={[742.147, -64.535, -508.885]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube003_spaceship_racer_0.geometry} material={materials.spaceship_racer} position={[737.618, 46.842, -176.413]} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder004_spaceship_racer_0.geometry} material={materials.spaceship_racer} position={[789.518, 59.453, -224.912]} rotation={[1.003, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube001_RExtr001_spaceship_racer_0.geometry} material={materials.spaceship_racer} position={[745.539, 159.319, -5.922]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube001_RPanel003_spaceship_racer_0.geometry} material={materials.spaceship_racer} position={[739.257, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube001_RPanel003_RExtr_spaceship_racer_0.geometry} material={materials.spaceship_racer} position={[739.257, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube002_spaceship_racer_0.geometry} material={materials.spaceship_racer} position={[736.789, -267.14, -33.214]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube001_RPanel001_spaceship_racer_0.geometry} material={materials.spaceship_racer} position={[739.257, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube001_RPanel003_RExtr001_spaceship_racer_0.geometry} material={materials.spaceship_racer} position={[739.257, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube005_cockpit_0.geometry} material={materials.cockpit} position={[739.446, 110.436, 307.179]} rotation={[0.087, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere_cockpit_0.geometry} material={materials.cockpit} position={[739.365, 145.689, 315.602]} rotation={[0.175, 0, 0]} />

      </group>
    </group>
  )
});

useGLTF.preload('models/rusty_spaceship.glb')
