name: Update Duolingo Streak

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update-streak:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch (con el script)
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install jsdom node-fetch

    - name: Run update-streak script
      run: node update-streak.mjs

    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages

    - name: Copy streak.json to gh-pages branch
      run: cp streak.json gh-pages/streak.json

    - name: Commit and push changes on gh-pages
      working-directory: gh-pages
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add streak.json
        git diff --cached --quiet || git commit -m "Update streak.json"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
